img_dir_1 : /hdd/wjb_data/AIBL/CLIP/img_dir_1.txt
img_dir_2 : /hdd/wjb_data/AIBL/CLIP/img_dir_2.txt
img_dir_3 : /hdd/wjb_data/AIBL/CLIP/img_dir_3.txt
img_dir_4 : /hdd/wjb_data/AIBL/CLIP/img_dir_4.txt
img_dir_5 : /hdd/wjb_data/AIBL/CLIP/img_dir_5.txt
img_dir_6 : /hdd/wjb_data/AIBL/CLIP/img_dir_6.txt
img_dir_7 : /hdd/wjb_data/AIBL/CLIP/img_dir_7.txt
img_dir_8 : /hdd/wjb_data/AIBL/CLIP/img_dir_8.txt
img_dir_9 : /hdd/wjb_data/AIBL/CLIP/img_dir_9.txt
img_dir_10 : /hdd/wjb_data/AIBL/CLIP/img_dir_10.txt
img_dir_11 : /hdd/wjb_data/AIBL/CLIP/img_dir_11.txt
img_dir_12 : /hdd/wjb_data/AIBL/CLIP/img_dir_12.txt
text_dir_1 : /hdd/wjb_data/AIBL/CLIP/text_dir_1.txt
text_dir_2 : /hdd/wjb_data/AIBL/CLIP/text_dir_2.txt
text_dir_3 : /hdd/wjb_data/AIBL/CLIP/text_dir_3.txt
text_dir_4 : /hdd/wjb_data/AIBL/CLIP/text_dir_4.txt
text_dir_5 : /hdd/wjb_data/AIBL/CLIP/text_dir_5.txt
text_dir_6 : /hdd/wjb_data/AIBL/CLIP/text_dir_6.txt
text_dir_7 : /hdd/wjb_data/AIBL/CLIP/text_dir_7.txt
text_dir_8 : /hdd/wjb_data/AIBL/CLIP/text_dir_8.txt
text_dir_9 : /hdd/wjb_data/AIBL/CLIP/text_dir_9.txt
text_dir_10 : /hdd/wjb_data/AIBL/CLIP/text_dir_10.txt
text_dir_11 : /hdd/wjb_data/AIBL/CLIP/text_dir_11.txt
text_dir_12 : /hdd/wjb_data/AIBL/CLIP/text_dir_12.txt
context_length : 88
